## Database
#MYSQL_USERNAME: root
#MYSQL_PASSWORD: Admin1234
#MYSQL_HOST: 127.0.0.1
#MYSQL_PORT: 3306
#MYSQL_DATABASE: securecapita
#
##Server Config
#CONTAINER_PORT: 8080
#ACTIVE_PROFILE: dev
#
##Email Config
#EMAIL_HOST: smtp.gmail.com
#EMAIL_PORT: 587
#EMAIL_ID: jaidmonwar.edu@gmail.com
#EMAIL_PASSWORD: wimv jjge dyhx xjyv
#VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}
#
#UI_APP_URL: http://localhost:4200
#
#JWT_SECRET: complexsecret
#
jwt:
  secret: complexsecret

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/securecapita
    password: Admin1234
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    propperties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: jaidmonwar.edu@gmail.com
    password: wimv jjge dyhx xjyv
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
