# Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: Admin1234
MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DATABASE: securecapita

#Server Config
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: jaidmonwar.edu@gmail.com
EMAIL_PASSWORD: wimv jjge dyhx xjyv
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

UI_APP_URL: http://localhost:4200

JWT_SECRET: complexsecret

